import {
  Lightbulb,
  Cog,
  UserRound,
  UsersRound,
  Home,
  ClipboardList,
  BriefcaseBusiness,
  ChartNoAxesCombined,
  History,
  Building,
  Pin,
  FolderArchive,
  Brain,
  Send,
  Target,
  Trophy,
  Files,
  ClipboardPenLine,
  NotebookPen,
  Users,
  Briefcase,
  PlaneTakeoff,
  Backpack,
  Tags,
  Settings2,
  Mails,
} from "lucide-react"

export const sidebarItems = [
  {
    title: "Home",
    url: "/dashboard",
    icon: Home,
  },
  {
    title: "My Profile",
    url: "/my-profile",
    icon: UserRound,
  },
  {
    title: "My Applications",
    url: "/my-applications",
    icon: ClipboardPenLine,
  },
  {
    title: "Careers",
    url: "/jobs",
    icon: NotebookPen,
  },
  {
    title: "Performance",
    url: "#",
    icon: ChartNoAxesCombined,
    roles: ["HRIS_Staff", "HRIS_DC", "HRIS_ADC", "HRIS_RD", "HRIS_ARD", "HRIS_HR", "HRIS_Administrator"],
    submenu: [
      { title: "Emails", url: "/emails", roles: ["HRIS_Staff", "HRIS_DC", "HRIS_ADC", "HRIS_RD", "HRIS_ARD", "HRIS_HR", "HRIS_Administrator"], icon: Mails },
      { title: "OPCR", url: "/opcrs", roles: ["HRIS_DC", "HRIS_RD", "HRIS_ARD"], icon: Building },
      { title: "DPCR", url: "/dpcrs", roles: ["HRIS_DC", "HRIS_ADC"], icon: UsersRound },
      { title: "IPCR", url: "/ipcrs", roles: ["HRIS_Staff"], icon: UserRound },
      { title: "Libraries", url: "/performance/libraries", roles: ["HRIS_HR", "HRIS_Administrator"], icon: FolderArchive },
    ],
  },
  {
    title: "Recruitment",
    url: "#",
    icon: BriefcaseBusiness,
    permissions: ["HRIS_recruitment.page.view"],
    submenu: [
      { title: "Applicants", url: "/applicants", permissions: ["HRIS_recruitment.applicants.page.view"], icon: Users },
      { title: "Applications", url: "/applications", permissions: ["HRIS_recruitment.applicants.page.view"], icon: Briefcase },
      { title: "Vacancies", url: "/vacancies", permissions: ["HRIS_recruitment.vacancies.page.view"], icon: ClipboardList },
      { title: "Publications", url: "/publications", permissions: ["HRIS_recruitment.publications.page.view"], icon: Pin },
    ],
  },
  {
    title: "Travels",
    url: "#",
    icon: PlaneTakeoff,
    permissions: ["HRIS_recruitment.page.view"],
    submenu: [
      { title: "Travel Requests", url: "/travel-requests", permissions: ["HRIS_travels.travel-requests.page.view"], icon: Backpack },
      { title: "Trip Tickets", url: "/trip-tickets", permissions: ["HRIS_travels.trip-tickets.page.view"], icon: Tags },
    ],
  },
  {
    title: "Flexiplace",
    url: "#",
    icon: History,
    permissions: ["HRIS_flexiplace.page.view"],
    submenu: [
      { title: "RTO", url: "/rto", permissions: ["HRIS_flexiplace.rto.page.view"], icon: Target },
      { title: "DTR", url: "/fwa", permissions: ["HRIS_flexiplace.dtr.page.view"], icon: History },
      { title: "RAA", url: "/raa", permissions: ["HRIS_flexiplace.raa.page.view"], icon: Trophy },
      { title: "Reports", url: "/fwa/reports", permissions: ["HRIS_flexiplace.reports.page.view"], icon: Files },
    ],
  },
  {
    title: "Competencies",
    url: "#",
    icon: Lightbulb,
    roles: ["HRIS_Staff"],
    submenu: [
      { title: "Gap Analysis", url: "/cga", roles: ["HRIS_Staff"], icon: Brain },
      { title: "Submissions", url: "/cga/review", roles: ["HRIS_HR", "HRIS_DC"], icon: Send },
      { title: "Libraries", url: "/cga/libraries", roles: ["HRIS_HR"], icon: Settings2 },
    ],
  },
  {
    title: "Settings",
    url: "/settings",
    icon: Cog,
    permissions: ["HRIS_settings.page.view"],
  },
]
